### ISSUE TITLE
zotero rectangle annotation

### ISSUE THREAD

**Issue by math-feng** [RyotaUshio/obsidian-pdf-plus#35] opened 2024-02-03 14:12 UTC
This plugin really amazes me and is my dream plugin! However, I feel very laggy while using it. I have an idea in the labeling of rectangular areas if it can be done by screenshot and can generate links like zotero's. Of course, I'm not familiar with programming, it's just a whim, thank you very much for developing this plugin!

**Comment by RyotaUshio** [comment] 2024-02-03 23:50
Thanks!
This is a duplicate of #1, so I'm closing this for now.

**Closed by RyotaUshio** 2024-02-03 23:50 UTC
