### ISSUE TITLE
Can you add support for scrolling up and down the mouse wheel on mobile for the PDF++ plug-in?

### ISSUE THREAD

**Issue by violentrant** [RyotaUshio/obsidian-pdf-plus#269] opened 2024-09-14 06:53 UTC
### Describe your request

Can you add support for scrolling up and down the mouse wheel on mobile for the PDF++ plug-in?
Sliding the scroll wheel on iPad OS allows you to scroll up and down to see different areas of the document displayed in PDF++

ipad os 17.5 obsidian

**Comment by iLiftALot** [comment] 2024-09-20 16:54
Yes please, this.

**Comment by RyotaUshio** [comment] 2024-09-23 17:19
Thanks, this seems to be a duplicate of #265, so I'm closing this issue.

**Closed by RyotaUshio** 2024-09-23 17:19 UTC
Labels: enhancement

**Comment by RyotaUshio** [comment] 2024-09-24 06:49
It turned out that this is not the same issue as #265.
This is a bug in Obsidian itself: https://forum.obsidian.md/t/ipados-ios-unable-to-scroll-pdfs-with-external-mouse-or-touchpad/87596
So I will wait the Obsidian team to fix it.

**Comment by violentrant** [comment] 2024-09-24 06:56
> It turned out that this is a separate issue from #265. This is a bug in Obsidian itself: https://forum.obsidian.md/t/ipados-ios-unable-to-scroll-pdfs-with-external-mouse-or-touchpad/87596 So I will wait the Obsidian team to fix it.

thank u for u reply, I don't know what the principle is, but the Excaldraw plugin can respond up and down to an external Bluetooth mouse on the iPad OS. If the plugin is inserted into a PDF file, it can also achieve mouse scrolling up and down. The Markmind plugin can also achieve mouse up and down scrolling on the iPad OS platform. I wonder if we can refer to the mechanism of their plugin to try to solve this problem, help ordinary users, and improve user experience.

**Comment by RyotaUshio** [comment] 2024-09-24 13:52
I wish I could, but it seems very difficult to fixed it from a plugin's code. I will try if I find a way.
