### ISSUE TITLE
[Bug] Backlink highlighting & cropped embeds not working if the page is rotated

### ISSUE THREAD

**Issue by sims0702** [RyotaUshio/obsidian-pdf-plus#84] opened 2024-03-04 14:27 UTC
### Steps to reproduce

I don't know, in a new test vault it is working however?
edit: it is actually only happening with one particular pdf.

### Expected behavior

Hey, I expected the rectangular clipping optoin available to get the whole page, but it just crops it for some reason even though I select the whole screen with the selection tool
![image](https://github.com/RyotaUshio/obsidian-pdf-plus/assets/73917633/ae768e01-ed7f-4778-8403-9b0e321fc5fd)

### Actual behavior

This is how it actually looks like even though I select the whole screen. Any suggestions on how to fix this? Yesterday f.e., this wasn't an issue.
![image](https://github.com/RyotaUshio/obsidian-pdf-plus/assets/73917633/780bfa58-c57a-4640-8d3a-7f5e69b71214)

### Screen recordings or screenshots (sandbox vault)

/

### Obsidian debug info

SYSTEM INFO:
	Obsidian version: v1.5.8
	Installer version: v1.5.8
	Operating system: Windows 10 Home 10.0.22631
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: light
	Community theme: AnuPpuccin v1.4.5
	Snippets enabled: 3
	Restricted mode: off
	Plugins installed: 12
	Plugins enabled: 10
		1: Paste URL into selection v1.7.0
		2: Hider v1.3.1
		3: Number Headings v1.16.0
		4: Linter v1.22.0
		5: Latex Suite v1.9.0
		6: Style Settings v1.0.7
		7: File Color v1.1.0
		8: BRAT v0.8.4
		9: PDF++ v0.37.10
		10: Image Toolkit v1.4.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

### PDF++ debug info

```json
{
    "settings": {
        "displayTextFormats": [
            {
                "name": "Obsidian default",
                "template": "{{file.basename}}, page {{page}}"
            },
            {
                "name": "Title & page",
                "template": "{{file.basename}}, p.{{pageLabel}}"
            },
            {
                "name": "Page only",
                "template": "p.{{pageLabel}}"
            },
            {
                "name": "Text",
                "template": "{{text}}"
            }
        ],
        "defaultDisplayTextFormatIndex": 0,
        "syncDisplayTextFormat": true,
        "syncDefaultDisplayTextFormat": false,
        "copyCommands": [
            {
                "name": "Quote",
                "template": "> ({{linkWithDisplay}})\n> {{selection}}\n"
            },
            {
                "name": "Link only",
                "template": "{{linkWithDisplay}}"
            },
            {
                "name": "Embed",
                "template": "!{{link}}"
            },
            {
                "name": "Callout",
                "template": "> [!{{calloutType}}|{{colorName}}] {{linkWithDisplay}}\n> {{text}}\n"
            },
            {
                "name": "Quote in callout",
                "template": "> [!{{calloutType}}|{{colorName}}] {{linkWithDisplay}}\n> > {{text}}\n> \n> "
            },
            {
                "name": "Create new note",
                "template": "{{app.vault.create(text + \".md\", linkWithDisplay).then((file) => app.workspace.getLeaf(true).openFile(file)), \"\"}}"
            }
        ],
        "useAnotherCopyTemplateWhenNoSelection": false,
        "copyTemplateWhenNoSelection": "{{linkToPageWithDisplay}}",
        "trimSelectionEmbed": true,
        "embedMargin": 50,
        "noSidebarInEmbed": true,
        "noSpreadModeInEmbed": true,
        "embedUnscrollable": false,
        "singleTabForSinglePDF": true,
        "highlightExistingTab": false,
        "existingTabHighlightOpacity": 0.5,
        "existingTabHighlightDuration": 0.75,
        "paneTypeForFirstPDFLeaf": "",
        "openLinkNextToExistingPDFTab": true,
        "openPDFWithDefaultApp": false,
        "openPDFWithDefaultAppAndObsidian": true,
        "focusObsidianAfterOpenPDFWithDefaultApp": true,
        "syncWithDefaultApp": false,
        "dontActivateAfterOpenPDF": true,
        "dontActivateAfterOpenMD": true,
        "highlightDuration": 0.75,
        "noTextHighlightsInEmbed": false,
        "noAnnotationHighlightsInEmbed": true,
        "persistentTextHighlightsInEmbed": true,
        "persistentAnnotationHighlightsInEmbed": false,
        "highlightBacklinks": true,
        "dblclickEmbedToOpenLink": true,
        "highlightBacklinksPane": true,
        "highlightOnHoverBacklinkPane": true,
        "backlinkHoverColor": "",
        "colors": {
            "Yellow": "#ffd000",
            "Red": "#ea5252",
            "Note": "#086ddd",
            "Important": "#bb61e5"
        },
        "defaultColor": "",
        "defaultColorPaletteItemIndex": 0,
        "syncColorPaletteItem": true,
        "syncDefaultColorPaletteItem": false,
        "colorPaletteInToolbar": true,
        "noColorButtonInColorPalette": true,
        "colorPaletteInEmbedToolbar": false,
        "showStatusInToolbar": true,
        "highlightColorSpecifiedOnly": false,
        "doubleClickHighlightToOpenBacklink": true,
        "hoverHighlightAction": "preview",
        "paneTypeForFirstMDLeaf": "right",
        "singleMDLeafInSidebar": true,
        "alwaysUseSidebar": true,
        "defaultColorPaletteActionIndex": 4,
        "syncColorPaletteAction": true,
        "syncDefaultColorPaletteAction": false,
        "proxyMDProperty": "PDF",
        "hoverPDFLinkToOpen": false,
        "ignoreHeightParamInPopoverPreview": true,
        "filterBacklinksByPageDefault": true,
        "showBacklinkToPage": true,
        "enableHoverPDFInternalLink": true,
        "recordPDFInternalLinkHistory": true,
        "alwaysRecordHistory": true,
        "renderMarkdownInStickyNote": true,
        "enablePDFEdit": true,
        "author": "******",
        "writeHighlightToFileOpacity": 0.2,
        "defaultWriteFileToggle": false,
        "syncWriteFileToggle": true,
        "syncDefaultWriteFileToggle": false,
        "enableAnnotationDeletion": true,
        "warnEveryAnnotationDelete": false,
        "warnBacklinkedAnnotationDelete": true,
        "enableAnnotationContentEdit": true,
        "enableEditEncryptedPDF": true,
        "pdfLinkColor": "#04a802",
        "pdfLinkBorder": false,
        "replaceContextMenu": true,
        "executeBuiltinCommandForOutline": true,
        "executeBuiltinCommandForZoom": true,
        "executeFontSizeAdjusterCommand": true,
        "closeSidebarWithShowCommandIfExist": true,
        "autoHidePDFSidebar": false,
        "outlineDrag": true,
        "outlineContextMenu": true,
        "outlineLinkDisplayTextFormat": "{{file.basename}}, {{text}}",
        "outlineLinkCopyFormat": "{{linkWithDisplay}}",
        "recordHistoryOnOutlineClick": true,
        "popoverPreviewOnOutlineHover": true,
        "thumbnailDrag": true,
        "thumbnailContextMenu": true,
        "thumbnailLinkDisplayTextFormat": "{{file.basename}}, page {{pageLabel}}",
        "thumbnailLinkCopyFormat": "{{linkWithDisplay}}",
        "recordHistoryOnThumbnailClick": true,
        "popoverPreviewOnThumbnailHover": true,
        "annotationPopupDrag": true,
        "useCallout": true,
        "calloutType": "PDF",
        "calloutIcon": "highlighter",
        "highlightBacklinksInEmbed": false,
        "highlightBacklinksInHoverPopover": false,
        "highlightBacklinksInCanvas": true,
        "clickPDFInternalLinkWithModifierKey": true,
        "clickOutlineItemWithModifierKey": true,
        "clickThumbnailWithModifierKey": true,
        "focusEditorAfterAutoPaste": true,
        "respectCursorPositionWhenAutoPaste": true,
        "autoFocus": true,
        "autoFocusTarget": "last-active-and-open-then-last-paste",
        "autoPasteTarget": "last-active-and-open-then-last-paste",
        "openAutoFocusTargetIfNotOpened": true,
        "howToOpenAutoFocusTargetIfNotOpened": "right",
        "closeHoverEditorWhenLostFocus": true,
        "closeSidebarWhenLostFocus": true,
        "openAutoFocusTargetInEditingView": true,
        "executeCommandWhenTargetNotIdentified": true,
        "commandToExecuteWhenTargetNotIdentified": "pdf-plus:create-new-note",
        "selectToCopyToggleRibbonIcon": true,
        "autoFocusToggleRibbonIcon": true,
        "viewSyncFollowPageNumber": true,
        "viewSyncPageDebounceInterval": 0.3,
        "openAfterExtractPages": true,
        "howToOpenExtractedPDF": "tab",
        "warnEveryPageDelete": false,
        "warnBacklinkedPageDelete": true,
        "extractPageInPlace": false,
        "askExtractPageInPlace": true,
        "pageLabelUpdateWhenInsertPage": "keep",
        "pageLabelUpdateWhenDeletePage": "keep",
        "pageLabelUpdateWhenExtractPage": "keep",
        "askPageLabelUpdateWhenInsertPage": true,
        "askPageLabelUpdateWhenDeletePage": true,
        "askPageLabelUpdateWhenExtractPage": true,
        "copyOutlineAsListFormat": "{{linkWithDisplay}}",
        "copyOutlineAsListDisplayTextFormat": "{{text}}",
        "copyOutlineAsHeadingsFormat": "{{text}}\n\n{{linkWithDisplay}}",
        "copyOutlineAsHeadingsDisplayTextFormat": "p.{{pageLabel}}",
        "copyOutlineAsHeadingsMinLevel": 2,
        "newFileNameFormat": "",
        "newFileTemplatePath": "",
        "newPDFLocation": "current",
        "newPDFFolderPath": "",
        "rectEmbedStaticImage": false,
        "rectImageFormat": "file",
        "rectImageExtension": "webp",
        "includeColorWhenCopyingRectLink": true,
        "backlinkIconSize": 50,
        "showBacklinkIconForSelection": false,
        "showBacklinkIconForAnnotation": false,
        "showBacklinkIconForOffset": true,
        "showBacklinkIconForRect": false,
        "showBoundingRectForBacklinkedAnnot": false,
        "hideReplyAnnotation": false
    },
    "styleSettings": {},
    "styleSheet": ".pdf-plus-backlink-highlight-layer .pdf-plus-backlink:not(.hovered-highlight)[data-highlight-color=\"yellow\"],\n.pdf-embed[data-highlight-color=\"yellow\"] .textLayer .mod-focused {\n    --pdf-plus-color: #ffd000;\n    --pdf-plus-backlink-icon-color: #ffd000;\n    --pdf-plus-rect-color: #ffd000;\n}\n.pdf-plus-backlink-highlight-layer .pdf-plus-backlink:not(.hovered-highlight)[data-highlight-color=\"red\"],\n.pdf-embed[data-highlight-color=\"red\"] .textLayer .mod-focused {\n    --pdf-plus-color: #ea5252;\n    --pdf-plus-backlink-icon-color: #ea5252;\n    --pdf-plus-rect-color: #ea5252;\n}\n.pdf-plus-backlink-highlight-layer .pdf-plus-backlink:not(.hovered-highlight)[data-highlight-color=\"note\"],\n.pdf-embed[data-highlight-color=\"note\"] .textLayer .mod-focused {\n    --pdf-plus-color: #086ddd;\n    --pdf-plus-backlink-icon-color: #086ddd;\n    --pdf-plus-rect-color: #086ddd;\n}\n.pdf-plus-backlink-highlight-layer .pdf-plus-backlink:not(.hovered-highlight)[data-highlight-color=\"important\"],\n.pdf-embed[data-highlight-color=\"important\"] .textLayer .mod-focused {\n    --pdf-plus-color: #bb61e5;\n    --pdf-plus-backlink-icon-color: #bb61e5;\n    --pdf-plus-rect-color: #bb61e5;\n}\n.pdf-plus-backlink-highlight-layer .pdf-plus-backlink:not(.hovered-highlight) {\n    --pdf-plus-color: rgb(var(--text-highlight-bg-rgb));\n    --pdf-plus-backlink-icon-color: rgb(var(--text-highlight-bg-rgb));\n    --pdf-plus-rect-color: rgb(var(--text-highlight-bg-rgb));\n}\n.pdf-plus-backlink-highlight-layer .pdf-plus-backlink.hovered-highlight {\n\t--pdf-plus-color: green;\n\t--pdf-plus-backlink-icon-color: green;\n   --pdf-plus-rect-color: green;\n}\n.pdf-plus-color-palette-item[data-highlight-color=\"yellow\"] > .pdf-plus-color-palette-item-inner {\n    background-color: #ffd000;\n}\n.pdf-plus-color-palette-item[data-highlight-color=\"red\"] > .pdf-plus-color-palette-item-inner {\n    background-color: #ea5252;\n}\n.pdf-plus-color-palette-item[data-highlight-color=\"note\"] > .pdf-plus-color-palette-item-inner {\n    background-color: #086ddd;\n}\n.pdf-plus-color-palette-item[data-highlight-color=\"important\"] > .pdf-plus-color-palette-item-inner {\n    background-color: #bb61e5;\n}\n.pdf-plus-color-palette-item:not([data-highlight-color]) > .pdf-plus-color-palette-item-inner {\n    background-color: transparent;\n}\n.workspace-leaf.pdf-plus-link-opened.is-highlighted::before {\n\topacity: 0.5;\n}\nbody {\n    --pdf-plus-yellow-rgb: 255, 208, 0\n}\nbody {\n    --pdf-plus-red-rgb: 234, 82, 82\n}\nbody {\n    --pdf-plus-note-rgb: 8, 109, 221\n}\nbody {\n    --pdf-plus-important-rgb: 187, 97, 229\n}\nbody {\n    --pdf-plus-default-color-rgb: var(--text-highlight-bg-rgb)\n}\n.callout[data-callout=\"pdf\"][data-callout-metadata=\"yellow\"] {\n\t--callout-color: var(--pdf-plus-yellow-rgb);\n   background-color: rgba(var(--callout-color), var(--pdf-plus-highlight-opacity, 0.2))\n}\n.callout[data-callout=\"pdf\"][data-callout-metadata=\"red\"] {\n\t--callout-color: var(--pdf-plus-red-rgb);\n   background-color: rgba(var(--callout-color), var(--pdf-plus-highlight-opacity, 0.2))\n}\n.callout[data-callout=\"pdf\"][data-callout-metadata=\"note\"] {\n\t--callout-color: var(--pdf-plus-note-rgb);\n   background-color: rgba(var(--callout-color), var(--pdf-plus-highlight-opacity, 0.2))\n}\n.callout[data-callout=\"pdf\"][data-callout-metadata=\"important\"] {\n\t--callout-color: var(--pdf-plus-important-rgb);\n   background-color: rgba(var(--callout-color), var(--pdf-plus-highlight-opacity, 0.2))\n}\n.callout[data-callout=\"pdf\"] {\n\t--callout-color: var(--pdf-plus-default-color-rgb);\n   background-color: rgba(var(--callout-color), var(--pdf-plus-highlight-opacity, 0.2))\n}\n.callout[data-callout=\"pdf\"] {\n   --callout-icon: lucide-highlighter;\n}"
}
```

### Error messages

none

**Comment by RyotaUshio** [comment] 2024-03-04 14:32
Hey, I appreciate your report, but I need more information to address this issue.
Please follow the instructions in the bug report template and see if the bug can be reproduced in the sandbox vault.
Also, please attach the PDF file you are facing the problem with and also the content of the markdown file you pasted the embed link to.

**Comment by RyotaUshio** [comment] 2024-03-04 14:38
I'm not sure but I have a rough guess - doesn't the bug occur only when you scroll in the PDF viewer while selecting the rectangle region?

**Comment by RyotaUshio** [comment] 2024-03-04 14:53
@sims0702 If you mind share the PDF publically, send it via email: ushio@ms.k.u-tokyo.ac.jp
Thanks!

**Comment by sims0702** [comment] 2024-03-04 15:22
Hey @RyotaUshio , I apologize! This is my first time writing to be honets. I wasn't really sure what had to be done. I have to say I just realized even more amazing functionalities that this plugin brings, so the development of this plugin is much appreciated!
It could be. I just tried another pdf and got the same thing actually.

I have to note, I did scroll whilst selecting a couple of times, yes.

On further notice.. I just made a selection and indeed, if I scroll with the selection option selecting, even if I am **not** selecting anything it will crop the image. If I don't do that, it doesn't. (see the .md file at the end, slide 20)

Once again much appreciated for the help and this wonderful plugin!
[2_Basic_circuit_elements.pdf](https://github
[capacitor.md](https://github.com/RyotaUshio/obsidian-pdf-plus/files/14483607/capacitor.md)
.com/RyotaUshio/obsidian-pdf-plus/files/14483602/2_Basic_circuit_elements.pdf)

**Comment by sims0702** [comment] 2024-03-04 15:23
[capacitor.md](https://github.com/RyotaUshio/obsidian-pdf-plus/files/14483612/capacitor.md)

[2_Basic_circuit_elements.pdf](https://github.com/RyotaUshio/obsidian-pdf-plus/files/14483617/2_Basic_circuit_elements.pdf)

**Comment by sims0702** [comment] 2024-03-04 16:49
Hey, it is actually an issue in another vault as well in another case. Whenever I try to select only f.e. the title of a slide, it won't give me that. The same issue as when scrolling basically.

**Comment by sims0702** [comment] 2024-03-04 17:10
@RyotaUshio hey, I have found what the problem is, when using rectangular selection ***parts of the slide***, the selection will be inverted! i.e. if I select the upper half of a slide, it will give me the **left half** of the slide. Try it out to see what I mean if necessary. I got the same behavior in a test vault as well. If necessary, I will make screenshots.

**Comment by RyotaUshio** [comment] 2024-03-05 09:53
You don't need to apologize! Thanks for sending the files.

Unfortunately, I couldn't reproduce it in my sandbox vault. Here's how it looks:

https://github.com/RyotaUshio/obsidian-pdf-plus/assets/72342591/7e57df9a-a4ec-4ed1-9ab4-afcdf5a1febd

Can you provide screen recordings showing how you select the rectangle region and paste the embed link?

**Comment by sims0702** [comment] 2024-03-05 12:05
![image](https://github.com/RyotaUshio/obsidian-pdf-plus/assets/73917633/41a081b0-74e9-41fe-9db6-8274ac539c6a)

**Comment by RyotaUshio** [comment] 2024-03-05 12:26
Thanks, in the video I don't see the markdown file that the link is pasted into. Is it opened in a different window?

**Comment by RyotaUshio** [comment] 2024-03-05 12:27
Okay reproduced!

**Comment by RyotaUshio** [comment] 2024-03-05 12:32
For future reference: this bug happens when the page is rotated

**Comment by sims0702** [comment] 2024-03-05 12:38
I see, thanks a lot for the help! I don't know if you mean the rotating option here or?
![image](https://github.com/RyotaUshio/obsidian-pdf-plus/assets/73917633/0a9a52a1-79cf-4ff8-b1ae-139545027ad6)

Because to be honest. I just downloaded the pdf, and moved it to obsidian so I am not entirely sure why it happened. Strange.

And yes! that was the next thing I was going to tell you about haha.. the highlighting is flipped as well. Should have been a red flag that something like that was up perhaps but I didn't think about that.

**Comment by sims0702** [comment] 2024-03-05 12:41
The exact file we are talking about isn't rotated when opened in chrome?

![image](https://github.com/RyotaUshio/obsidian-pdf-plus/assets/73917633/fc88da9a-e388-4567-9c72-7e4b393799a0)

**Comment by RyotaUshio** [comment] 2024-03-05 12:49
Yeah so "rotation" here is a technical term in the PDF specification.
Each page in your PDF is in fact rotated by -90 degrees, and it is displayed after rotating by +90 degrees so that it can be viewed normally.
It's something going on under the hood and we users don't notice.

**Comment by sims0702** [comment] 2024-03-05 13:05
oh dear, I didn't know that.. so how can I fix that for this particular file then if you don't mind me asking?

**Comment by RyotaUshio** [comment] 2024-03-05 13:10
Unfortunately, it can only be fixed by PDF++ itself and I have to ask you to wait until that. Sorry for the inconvenience!

**Comment by sims0702** [comment] 2024-03-05 13:53
oh sure! No worries at all. Thanks for taking the time anyways!

**Comment by RyotaUshio** [comment] 2024-03-05 14:19
I was able to fix the positioning of backlink highlights, and I will also fix the cropped embeds later:

https://github.com/RyotaUshio/obsidian-pdf-plus/assets/72342591/cff9b59c-26ee-42de-85d6-2c1d45835a02

Unfortunately, you may have to re-paste all the rectangle embeds from that PDF file.

**Comment by RyotaUshio** [comment] 2024-03-05 15:12
Fixed! Hang on tight until the next release.

https://github.com/RyotaUshio/obsidian-pdf-plus/assets/72342591/a5436659-b948-4338-80d5-3d0d98dcba8e

I appreciate your report, I could not have found this bug alone. Thank you so much!

**Closed by RyotaUshio** 2024-03-05 15:12 UTC
Labels: bug

**Comment by sims0702** [comment] 2024-03-05 15:19
You are such a beat hehe! Amazing. Talk to me if you ever need any help. Would be glad to help, you have my email.
Btw if you don't mind me asking, if it's appropriate to ask here.. how do you use and organize your notes? I try to use a lot of backlinking for concepts in a particular subject but I am not sure whether that is really helpful.. 

I also just figured out the smart connecdtions plugin which can automatically give you those connections.

**Comment by RyotaUshio** [comment] 2024-03-05 16:09
I haven't tried Smart Connections but sounds interesting.
I haven't fully established my own workflow but I'd suggest avoiding overthink.
Back when I was using LaTeX (OverLeaf) to organize all of my notes, I would often wonder if I could link my ideas distributed across the entire document to each other... and now it's possible thanks to Obsidian so I just do so. In other words, I use Obsidian as OverLeaf with a more powerful linking function.

To be honest I'm not very interested in fancy PKM methodologies... The most important thing is to just write a lot, and thinking about the methodology too much prevents us from that.

Maybe this is not very helpful advice but my rule of thumb is just to focus on writing and refrain from being distracted by anything that can stop your writing. (I'm creating my own plugin so I'm obviously violating this rule haha)

**Comment by sims0702** [comment] 2024-03-05 17:01
@RyotaUshio, Thanks! That's solid advice for sure, that is how today went to be honest hahahah..


I am just thinking about whether the way I am doing it is useful. It feels like I am doing a bit too much linking in my notes at times. (--> leading to wasting too much time because I want to capture 'everything') f.e. subject: computer architecture, then I would create a link [[memories]] and other high level concepts like CPU and then in memories I would create different notes for the different memories themselves like RAM, ROM, flash, ... which are then explained in their own notes. Kind of treating it concept-based. But I feel that it takes too much time sometimes.

For some context, before this I used to never take notes besides the ones from class and then study the slide with notes which didn't really give me any structure. :'D Hence, now I am trying out obsidian.

For smartconnections, honestly, I have been looking at it for the past 1.5 hours and it's pretty solid. It basically makes the connections with a specific note for us which means that linking manually becomes kind of useless (I guess all of my efforts just become wasted time!...), besides that by manually linking you get the connections shown in the **graph** view.

And I wouldn't say you are wasting your time with it tho! To say the least,  because of you I have no need of Onenote at all anymore. Let alone to start talking about the embedding features for pdfs and 50+ more options I haven't even used yet. And also, from every experience you have, you learn as well even if you're not writing but developing a plugin instead. You can write notes for 10 years and keep writing without undertaking any action. But what do you achieve that way? **a big fat nothing** :)
