### ISSUE TITLE
[FR] Extract Highlights

### ISSUE THREAD

**Issue by Friedolito** [RyotaUshio/obsidian-pdf-plus#49] opened 2024-02-16 22:43 UTC
First of all thanks!! 
I never really used PDF in obsmd, but it's now changing and that in part of PDF++.
I just scrolled trough the settings and it's crazy how big this is. Props! 

One thing I would find really useful, is to extract all highlights of a PDF and be able to paste them in a .md file, with the backlinks to the pdf. 
I think it's something a lot of people could find helpful. :)

**Comment by RyotaUshio** [comment] 2024-02-17 08:18
Thanks!

So your idea is that, although we are already able to copy & paste each highlighted text with a link to the corresponding location in the PDF one by one manually, it would be even better if we could do this for all highlights just by running a single command or something, right?

I agree such a functionality will be useful especially for those who already have a bunch of PDFs with highlights.

**Comment by Friedolito** [comment] 2024-02-17 08:32
Exactly! 
So it fits in a process of first reading the pdf and highlighting, then exporting those highlights and then working with them in obsmd.

**Comment by RyotaUshio** [comment] 2024-02-17 09:09
I see, my question is then why don't you add highlights in Obsidian?

https://github.com/RyotaUshio/obsidian-pdf-plus/assets/72342591/5d9f7f81-04d8-4baf-a2c1-5db5c2781d01

Setups:

- Install PDF++ ver. >= 0.35.12
- Assign a hotkey `cmd`+`opt`+`C` to the command "Copy & auto-paste link to selection or annotation"
- In PDF++ settings:
  - Enable editing PDF files and set the annotation author-name
     <img width="662" alt="image" src="https://github.com/RyotaUshio/obsidian-pdf-plus/assets/72342591/a916939b-d311-4276-8711-4bb92dd56895">
  - in the auto-paste options, set "How to open target markdown file if not opened" to "RIght sidebar"
    <img width="614" alt="image" src="https://github.com/RyotaUshio/obsidian-pdf-plus/assets/72342591/54d57635-36a2-4220-b2b2-fa30648da1bb">
- In the PDF toolbar, turn on the toggle "Write to file directly"

After that, you will be able to use the hotkey `cmd`+`opt`+`C` to add a highlight to the selected text and auto-paste the formatted link to a markdown file.

**Comment by RyotaUshio** [comment] 2024-02-17 14:20
Released in [0.35.13](https://github.com/RyotaUshio/obsidian-pdf-plus/releases/tag/0.35.13)!

**Closed by RyotaUshio** 2024-02-17 14:20 UTC

**Comment by Friedolito** [comment] 2024-02-17 21:25
Damn, this is fast!!
Thank you so much, for putting it in :) !
(Is there an way to change the layout of the extraction? Is it via the custom CSS file?)

I have my workflow with an Ipad and highlighting there. 
For me its a more natural way to read. 
But I will check out the set-up in obsidian, and see if it works for me.

**Comment by RyotaUshio** [comment] 2024-02-18 04:12
> Is there any way to change the layout of the extraction? Is it via the custom CSS file?

What do you mean by "layout"? If you are referring to the template, you can change it from the dropdown menu in the PDF toolbar.

<img width="773" alt="image" src="https://github.com/RyotaUshio/obsidian-pdf-plus/assets/72342591/c8be18ec-5044-463f-9b51-2697435ce8b4">

<img width="776" alt="image" src="https://github.com/RyotaUshio/obsidian-pdf-plus/assets/72342591/4f5079dd-5d89-4368-865d-8a3fd2f199dd">

You can also add your own custom template from here:

<img width="666" alt="image" src="https://github.com/RyotaUshio/obsidian-pdf-plus/assets/72342591/9717bb90-07f8-4909-bc8e-3e7f82bf3782">

For the colored callouts, see here in the settings pane:

<img width="664" alt="image" src="https://github.com/RyotaUshio/obsidian-pdf-plus/assets/72342591/6e38b767-f3c3-4e5b-a218-6402e7cc1b22">

**Comment by Friedolito** [comment] 2024-02-18 20:46
Neat! This is exactly what I wanted 😇
But I played around a bit and probably broke s.t. :D 
No I can't open any PDF anymore, it just shows a blank tab. 
This is what the developer console shows: 
<img width="1064" alt="Screenshot -2024-02-18 at 21 45 37@2x" src="https://github.com/RyotaUshio/obsidian-pdf-plus/assets/53973194/73bba7d3-0970-44c4-9505-988823b39bf3">


Should I open i seperate issue?

**Comment by Friedolito** [comment] 2024-02-18 20:55
Neat that is exactly what I wanted 😇

But I played around a bit and now it is broken :D 
The PDFs won't open anymore, its just a blank tab. 

The developer consoles displays: 
<img width="1064" alt="Screenshot -2024-02-18 at 21 45 37@2x" src="https://github.com/RyotaUshio/obsidian-pdf-plus/assets/53973194/8be723bc-767a-45da-8b7b-f2c64cb0fc69">

Should I open a seperate issue?

**Comment by RyotaUshio** [comment] 2024-02-18 21:09
That's strange, I have never seen that error...

> Should I open a seperate issue?

Yes, please! Providing the following information will help me identify the cause of the problem:

1. From the command palette, run the command "Show debug info" and copy & paste the result
2. Again, from the command palette, execude the command "PDF++: copy debug info" and then paste the result

**Comment by RyotaUshio** [comment] 2024-02-18 21:12
FYI, _if you don't mind losing your PDF++ settings_, deleting `<VAULT ROOT FOLDER>/.obsidian/plugins/pdf-plus/data.json` and reloading the plugin will fix the issue.
